include(FindPackageHandleStandardArgs)

SET(INCLUDE_SEARCH_PATHS
 $ENV{BLAS_CLASSES_DIR}
 ${BLAS_CLASSES_DIR}
 ${DMFT_DIR}/blas_classes
 ${DMFT_DIR}/include
 ${CMAKE_SOURCE_DIR}
 ${CMAKE_SOURCE_DIR}/blas_classes
 ${CMAKE_SOURCE_DIR}/..
 )

FIND_PATH(BLAS_CLASSES_INCLUDE_DIR blasheader.h ${INCLUDE_SEARCH_PATHS} DOC "BLAS classes include path")

FIND_PACKAGE_HANDLE_STANDARD_ARGS(BLAS_CLASSES DEFAULT_MSG BLAS_CLASSES_INCLUDE_DIR)
